[package]
name = "git-wrapped"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = "0.10.4"
resvg = { version = "=0.48.1", default-features = false, features = ["text"] }
globset = "0.4.20"
ctrlc = "3.5.2"
image = { version = "0.25", default-features = false, features = ["gif"] }

[dev-dependencies]
tempfile = "3"
